# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path
name: Ubuntu

on:
  push:
    branches:
      - 'master'
      - 'release-*'
jobs:
  install_backend:
    runs-on: ubuntu-latest
    env:
       working-directory: ./backend
    steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 14
       uses: actions/setup-java@v1
       with:
         java-version: 14
     - name: Cache Maven packages
       uses: actions/cache@v2
       with:
         path: ~/.m2
         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os }}-m2
     - name: Build with Maven
       run: mvn -B install --file pom.xml
       working-directory: ${{env.working-directory}}
     - run: mkdir staging && cp -R backend/target/*.jar staging
     - uses: actions/upload-artifact@v2
       with:
         name: Package
         path: staging
  build_package:
    runs-on: ubuntu-latest
    env:
       working-directory: ./frontend
    steps:
     - uses: actions/checkout@v2
     - name: Set up JDK 14
       uses: actions/setup-java@v1
       with:
         java-version: 14
     - name: Cache Maven packages
       uses: actions/cache@v2
       with:
         path: ~/.m2
         key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
         restore-keys: ${{ runner.os }}-m2
     - name: Build Frontend
       run: mvn -B package --file pom.xml
       working-directory: ${{env.working-directory}}
     - run: mkdir staging && cp -R backend/target/*.jar staging
     - uses: actions/upload-artifact@v2
       with:
         name: Package
         path: staging


